language: objective-c
osx_image: xcode10.2
install:
    - gem install cocoapods
    - gem install xcpretty
    - gem install xcpretty-travis-formatter
script:
    - export LC_ALL=en_US.UTF-8
    - set -o pipefail && xcodebuild clean -project ContextLabel.xcodeproj  -scheme ContextLabel CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`
    - set -o pipefail && xcodebuild test -project ContextLabel.xcodeproj -scheme ContextLabel -destination 'platform=iOS Simulator,name=iPhone 6s,OS=12.1' CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`
notifications:
  email:
on_success: never